main: task4

task1: task1.c
	gcc task1.c -o task1.out

task2: task2.c
	gcc task2.c -o task2.out

task3: task3.c
	gcc task3.c -o task3.out

task4: task4.c
	gcc task4.c -o task4.out

clean:
	rm -rf *out